### ISSUE TITLE
Transfer to adopted-ember-addons

### ISSUE THREAD

**Issue by RobbieTheWagner** [adopted-ember-addons/ember-cli-chart#145]
@aomran are you still interested in maintaining this addon? If not, could I suggest you transfer it to adopted-ember-addons? Then we can have a team of maintainers help keep it up to date.

**Comment by derrabauke** [comment]
bump :up:

**Comment by RobbieTheWagner** [comment]
@derrabauke there was no previous interest from @aomran to move this to adopted-ember-addons, but I was able to get permissions to this repo. What can I help with?

**Comment by derrabauke** [comment]
Hey @RobbieTheWagner, thanks for the fast response! I had difficulties to get a plugin running which needs `chartjs` v4. First I looked for the latest release `v3.7.2` of `ember-cli-chart` and it is on `chartjs: ^v2.9.0`. Having a look at the `master` revealed some work of yours bumping it to `v4`. I was just wondering if you would want to release this someday? Or does it need some work to be done?

For my special case I could find an older version of the plugin which works with v3 of chartjs, so I'm fine for the moment. But I guess it could be interesting for other as well to have the latest chartjs version available. :shrug:

**Comment by RobbieTheWagner** [comment]
@derrabauke the one thing that is not working is updating the charts. The initial render works great on master, but I do not know why the charts will not update when new data is passed. If you have some time to help debug that, and we can get it fixed, we can definitely release a new version.

**Comment by aomran** [comment]
Apologies for not seeing this. I have no issues with moving this to adopted-ember-addons. What's the process for doing this?

**Comment by MelSumner** [comment]
@aomran Here's the process: https://github.com/adopted-ember-addons/program-guidelines 👍

**Comment by MichalBryxi** [comment]
@aomran humble ping

**Comment by aomran** [comment]
I posted on the discord channel. Waiting for the transfer process to start.

**Comment by RobbieTheWagner** [comment]
@aomran you can transfer to me if you'd like and I can transfer it to adopted-ember-addons

**Comment by aomran** [comment]
@RobbieTheWagner it says "RobbieTheWagner/ember-cli-chart already exists"

**Comment by RobbieTheWagner** [comment]
> @RobbieTheWagner it says "RobbieTheWagner/ember-cli-chart already exists"

@aomran ah I guess I need to delete my fork first

**Comment by RobbieTheWagner** [comment]
@aomran I deleted my fork, can you please try now?

**Comment by RobbieTheWagner** [comment]
This has been transferred now 🎉
